// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BrevoApi from "../../../index.js";

export declare namespace TransactionalEmailsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TransactionalEmailsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TransactionalEmailsClient.Options>;

    constructor(options: TransactionalEmailsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {BrevoApi.GetTransacBlockedContactsRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.getTransacBlockedContacts()
     */
    public getTransacBlockedContacts(
        request: BrevoApi.GetTransacBlockedContactsRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetTransacBlockedContactsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTransacBlockedContacts(request, requestOptions));
    }

    private async __getTransacBlockedContacts(
        request: BrevoApi.GetTransacBlockedContactsRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetTransacBlockedContactsResponse>> {
        const { startDate, endDate, limit, offset, senders, sort } = request;
        const _queryParams: Record<string, unknown> = {
            startDate,
            endDate,
            limit,
            offset,
            senders,
            sort: sort != null ? sort : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/blockedContacts",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetTransacBlockedContactsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/smtp/blockedContacts");
    }

    /**
     * @param {BrevoApi.DeleteSmtpBlockedContactsEmailRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.transactionalEmails.unblockOrResubscribeATransactionalContact({
     *         email: "email"
     *     })
     */
    public unblockOrResubscribeATransactionalContact(
        request: BrevoApi.DeleteSmtpBlockedContactsEmailRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(
            this.__unblockOrResubscribeATransactionalContact(request, requestOptions),
        );
    }

    private async __unblockOrResubscribeATransactionalContact(
        request: BrevoApi.DeleteSmtpBlockedContactsEmailRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { email } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/blockedContacts/${core.url.encodePathParam(email)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/smtp/blockedContacts/{email}",
        );
    }

    /**
     * Get the list of blocked domains
     *
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.transactionalEmails.getBlockedDomains()
     */
    public getBlockedDomains(
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetBlockedDomainsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getBlockedDomains(requestOptions));
    }

    private async __getBlockedDomains(
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetBlockedDomainsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/blockedDomains",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetBlockedDomainsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.BrevoApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/smtp/blockedDomains");
    }

    /**
     * Blocks a new domain in order to avoid messages being sent to the same
     *
     * @param {BrevoApi.BlockNewDomainRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.blockNewDomain({
     *         domain: "example.com"
     *     })
     */
    public blockNewDomain(
        request: BrevoApi.BlockNewDomainRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__blockNewDomain(request, requestOptions));
    }

    private async __blockNewDomain(
        request: BrevoApi.BlockNewDomainRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/blockedDomains",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/smtp/blockedDomains");
    }

    /**
     * Unblocks an existing domain from the list of blocked domains
     *
     * @param {BrevoApi.DeleteBlockedDomainRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.transactionalEmails.deleteBlockedDomain({
     *         domain: "domain"
     *     })
     */
    public deleteBlockedDomain(
        request: BrevoApi.DeleteBlockedDomainRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteBlockedDomain(request, requestOptions));
    }

    private async __deleteBlockedDomain(
        request: BrevoApi.DeleteBlockedDomainRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { domain } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/blockedDomains/${core.url.encodePathParam(domain)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/smtp/blockedDomains/{domain}",
        );
    }

    /**
     * Delete hardbounces. To use carefully (e.g. in case of temporary ISP failures)
     *
     * @param {BrevoApi.DeleteHardbouncesRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.deleteHardbounces()
     */
    public deleteHardbounces(
        request: BrevoApi.DeleteHardbouncesRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteHardbounces(request, requestOptions));
    }

    private async __deleteHardbounces(
        request: BrevoApi.DeleteHardbouncesRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/deleteHardbounces",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/smtp/deleteHardbounces");
    }

    /**
     * @param {BrevoApi.SendTransacEmailRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.sendTransacEmail({
     *         htmlContent: "<html><head></head><body><p>Hello,</p>This is my first transactional email sent from Brevo.</p></body></html>",
     *         sender: {
     *             email: "hello@brevo.com",
     *             name: "Alex from Brevo"
     *         },
     *         subject: "Hello from Brevo!",
     *         to: [{
     *                 email: "johndoe@example.com",
     *                 name: "John Doe"
     *             }]
     *     })
     *
     * @example
     *     await client.transactionalEmails.sendTransacEmail({
     *         htmlContent: "<html><head></head><body>Your delivery is expected {{params.estimatedArrival}}.Your tracking code: {{params.trackingCode}}</p></body></html>",
     *         params: {
     *             "trackingCode": "JD01460000300002350000",
     *             "estimatedArrival": "Tomorrow"
     *         },
     *         sender: {
     *             email: "hello@brevo.com",
     *             name: "Alex from Brevo"
     *         },
     *         subject: "Hello from Brevo!",
     *         to: [{
     *                 email: "johndoe@example.com",
     *                 name: "John Doe"
     *             }]
     *     })
     */
    public sendTransacEmail(
        request: BrevoApi.SendTransacEmailRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.SendTransacEmailResponse> {
        return core.HttpResponsePromise.fromPromise(this.__sendTransacEmail(request, requestOptions));
    }

    private async __sendTransacEmail(
        request: BrevoApi.SendTransacEmailRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.SendTransacEmailResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/email",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.SendTransacEmailResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/smtp/email");
    }

    /**
     * Delete scheduled batch of emails by batchId or single scheduled email by messageId
     *
     * @param {BrevoApi.DeleteScheduledEmailByIdRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.transactionalEmails.deleteScheduledEmailById({
     *         identifier: "4320f270-a4e3-4a2e-b591-edfe30a5e627"
     *     })
     */
    public deleteScheduledEmailById(
        request: BrevoApi.DeleteScheduledEmailByIdRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteScheduledEmailById(request, requestOptions));
    }

    private async __deleteScheduledEmailById(
        request: BrevoApi.DeleteScheduledEmailByIdRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { identifier } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/email/${core.url.encodePathParam(identifier)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/smtp/email/{identifier}");
    }

    /**
     * Fetch scheduled batch of emails by batchId or single scheduled email by messageId (Can retrieve data upto 30 days old)
     *
     * @param {BrevoApi.GetScheduledEmailByIdRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.transactionalEmails.getScheduledEmailById({
     *         identifier: "4320f270-a4e3-4a2e-b591-edfe30a5e627",
     *         startDate: "2022-02-02",
     *         endDate: "2022-03-02"
     *     })
     */
    public getScheduledEmailById(
        request: BrevoApi.GetScheduledEmailByIdRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetScheduledEmailByIdResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getScheduledEmailById(request, requestOptions));
    }

    private async __getScheduledEmailById(
        request: BrevoApi.GetScheduledEmailByIdRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetScheduledEmailByIdResponse>> {
        const { identifier, startDate, endDate, sort, status, limit, offset } = request;
        const _queryParams: Record<string, unknown> = {
            startDate: startDate != null ? startDate : undefined,
            endDate: endDate != null ? endDate : undefined,
            sort: sort != null ? sort : undefined,
            status: status != null ? status : undefined,
            limit,
            offset,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/emailStatus/${core.url.encodePathParam(identifier)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetScheduledEmailByIdResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/smtp/emailStatus/{identifier}",
        );
    }

    /**
     * This endpoint will show the list of emails for past 30 days by default. To retrieve emails before that time, please pass startDate and endDate in query filters.
     *
     * @param {BrevoApi.GetTransacEmailsListRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.getTransacEmailsList()
     */
    public getTransacEmailsList(
        request: BrevoApi.GetTransacEmailsListRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetTransacEmailsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTransacEmailsList(request, requestOptions));
    }

    private async __getTransacEmailsList(
        request: BrevoApi.GetTransacEmailsListRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetTransacEmailsListResponse>> {
        const { email, templateId, messageId, startDate, endDate, sort, limit, offset } = request;
        const _queryParams: Record<string, unknown> = {
            email,
            templateId,
            messageId,
            startDate,
            endDate,
            sort: sort != null ? sort : undefined,
            limit,
            offset,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/emails",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetTransacEmailsListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/smtp/emails");
    }

    /**
     * <Note title="How to get uuid?">
     * You can get the uuid using either of the following methods:
     *
     * Send a GET request to https://api.brevo.com/v3/smtp/emails and pass the message_id in the url. Use your api-key to authenticate the request and you will get your uuid as a response.
     *
     * The uuid can also be fetched from the transactional logs page in your Brevo account, from the address URL.
     * </Note>
     *
     * @param {BrevoApi.GetTransacEmailContentRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.transactionalEmails.getTransacEmailContent({
     *         uuid: "uuid"
     *     })
     */
    public getTransacEmailContent(
        request: BrevoApi.GetTransacEmailContentRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetTransacEmailContentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTransacEmailContent(request, requestOptions));
    }

    private async __getTransacEmailContent(
        request: BrevoApi.GetTransacEmailContentRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetTransacEmailContentResponse>> {
        const { uuid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/emails/${core.url.encodePathParam(uuid)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetTransacEmailContentResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.BrevoApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/smtp/emails/{uuid}");
    }

    /**
     * @param {BrevoApi.DeleteSmtpLogIdentifierRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.transactionalEmails.deleteAnSmtpTransactionalLog({
     *         identifier: "identifier"
     *     })
     */
    public deleteAnSmtpTransactionalLog(
        request: BrevoApi.DeleteSmtpLogIdentifierRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAnSmtpTransactionalLog(request, requestOptions));
    }

    private async __deleteAnSmtpTransactionalLog(
        request: BrevoApi.DeleteSmtpLogIdentifierRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { identifier } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/log/${core.url.encodePathParam(identifier)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/smtp/log/{identifier}");
    }

    /**
     * This endpoint will show the aggregated stats for past 90 days by default if `startDate` and `endDate` OR `days` is not passed. The date range can not exceed 90 days
     *
     * @param {BrevoApi.GetAggregatedSmtpReportRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.getAggregatedSmtpReport()
     */
    public getAggregatedSmtpReport(
        request: BrevoApi.GetAggregatedSmtpReportRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetAggregatedSmtpReportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getAggregatedSmtpReport(request, requestOptions));
    }

    private async __getAggregatedSmtpReport(
        request: BrevoApi.GetAggregatedSmtpReportRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetAggregatedSmtpReportResponse>> {
        const { startDate, endDate, days, tag } = request;
        const _queryParams: Record<string, unknown> = {
            startDate,
            endDate,
            days,
            tag,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/statistics/aggregatedReport",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetAggregatedSmtpReportResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/smtp/statistics/aggregatedReport",
        );
    }

    /**
     * This endpoint will show the aggregated stats for past 30 days by default if `startDate` and `endDate` OR `days` is not passed. The date range can not exceed 90 days
     *
     * @param {BrevoApi.GetEmailEventReportRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.getEmailEventReport()
     */
    public getEmailEventReport(
        request: BrevoApi.GetEmailEventReportRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetEmailEventReportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getEmailEventReport(request, requestOptions));
    }

    private async __getEmailEventReport(
        request: BrevoApi.GetEmailEventReportRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetEmailEventReportResponse>> {
        const { limit, offset, startDate, endDate, days, email, event, tags, messageId, templateId, sort } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            startDate,
            endDate,
            days,
            email,
            event: event != null ? event : undefined,
            tags,
            messageId,
            templateId,
            sort: sort != null ? sort : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/statistics/events",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetEmailEventReportResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/smtp/statistics/events");
    }

    /**
     * @param {BrevoApi.GetSmtpReportRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.getSmtpReport()
     */
    public getSmtpReport(
        request: BrevoApi.GetSmtpReportRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetSmtpReportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSmtpReport(request, requestOptions));
    }

    private async __getSmtpReport(
        request: BrevoApi.GetSmtpReportRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetSmtpReportResponse>> {
        const { limit, offset, startDate, endDate, days, tag, sort } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            startDate,
            endDate,
            days,
            tag,
            sort: sort != null ? sort : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/statistics/reports",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetSmtpReportResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/smtp/statistics/reports");
    }

    /**
     * @param {unknown} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.postPreviewSmtpEmailTemplates({
     *         "key": "value"
     *     })
     */
    public postPreviewSmtpEmailTemplates(
        request?: unknown,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.PostPreviewSmtpEmailTemplatesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postPreviewSmtpEmailTemplates(request, requestOptions));
    }

    private async __postPreviewSmtpEmailTemplates(
        request?: unknown,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.PostPreviewSmtpEmailTemplatesResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/template/preview",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.PostPreviewSmtpEmailTemplatesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/smtp/template/preview");
    }

    /**
     * @param {BrevoApi.GetSmtpTemplatesRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.getSmtpTemplates()
     */
    public getSmtpTemplates(
        request: BrevoApi.GetSmtpTemplatesRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetSmtpTemplatesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSmtpTemplates(request, requestOptions));
    }

    private async __getSmtpTemplates(
        request: BrevoApi.GetSmtpTemplatesRequest = {},
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetSmtpTemplatesResponse>> {
        const { templateStatus, limit, offset, sort } = request;
        const _queryParams: Record<string, unknown> = {
            templateStatus,
            limit,
            offset,
            sort: sort != null ? sort : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/templates",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetSmtpTemplatesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/smtp/templates");
    }

    /**
     * @param {BrevoApi.CreateSmtpTemplateRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.transactionalEmails.createSmtpTemplate({
     *         sender: {},
     *         subject: "Thanks for your purchase !",
     *         templateName: "Order Confirmation - EN"
     *     })
     */
    public createSmtpTemplate(
        request: BrevoApi.CreateSmtpTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.CreateSmtpTemplateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createSmtpTemplate(request, requestOptions));
    }

    private async __createSmtpTemplate(
        request: BrevoApi.CreateSmtpTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.CreateSmtpTemplateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "smtp/templates",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.CreateSmtpTemplateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/smtp/templates");
    }

    /**
     * @param {BrevoApi.GetSmtpTemplateRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.transactionalEmails.getSmtpTemplate({
     *         templateId: 1000000
     *     })
     */
    public getSmtpTemplate(
        request: BrevoApi.GetSmtpTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetSmtpTemplateOverview> {
        return core.HttpResponsePromise.fromPromise(this.__getSmtpTemplate(request, requestOptions));
    }

    private async __getSmtpTemplate(
        request: BrevoApi.GetSmtpTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetSmtpTemplateOverview>> {
        const { templateId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/templates/${core.url.encodePathParam(templateId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetSmtpTemplateOverview, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/smtp/templates/{templateId}");
    }

    /**
     * @param {BrevoApi.UpdateSmtpTemplateRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.transactionalEmails.updateSmtpTemplate({
     *         templateId: 1000000
     *     })
     */
    public updateSmtpTemplate(
        request: BrevoApi.UpdateSmtpTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__updateSmtpTemplate(request, requestOptions));
    }

    private async __updateSmtpTemplate(
        request: BrevoApi.UpdateSmtpTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { templateId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/templates/${core.url.encodePathParam(templateId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/smtp/templates/{templateId}");
    }

    /**
     * @param {BrevoApi.DeleteSmtpTemplateRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.transactionalEmails.deleteSmtpTemplate({
     *         templateId: 1000000
     *     })
     */
    public deleteSmtpTemplate(
        request: BrevoApi.DeleteSmtpTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSmtpTemplate(request, requestOptions));
    }

    private async __deleteSmtpTemplate(
        request: BrevoApi.DeleteSmtpTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { templateId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/templates/${core.url.encodePathParam(templateId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/smtp/templates/{templateId}",
        );
    }

    /**
     * @param {BrevoApi.SendTestTemplateRequest} request
     * @param {TransactionalEmailsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.transactionalEmails.sendTestTemplate({
     *         templateId: 1000000,
     *         body: {}
     *     })
     */
    public sendTestTemplate(
        request: BrevoApi.SendTestTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__sendTestTemplate(request, requestOptions));
    }

    private async __sendTestTemplate(
        request: BrevoApi.SendTestTemplateRequest,
        requestOptions?: TransactionalEmailsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { templateId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `smtp/templates/${core.url.encodePathParam(templateId)}/sendTest`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/smtp/templates/{templateId}/sendTest",
        );
    }
}
