# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class UpdateCouponCollectionResponse(UniversalBaseModel):
    default_coupon: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="defaultCoupon"),
        pydantic.Field(alias="defaultCoupon", description="The default coupon of the collection"),
    ]
    id: str = pydantic.Field()
    """
    The id of the collection
    """

    name: str = pydantic.Field()
    """
    The name of the collection
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
