// This file was auto-generated by Fern from our API Definition.

import type * as BrevoApi from "../../../../index.js";

/**
 * @example
 *     {
 *         action: "resend",
 *         email: "email"
 *     }
 */
export interface PutCorporateUserInvitationActionEmailRequest {
    /** Action to be performed (cancel / resend) */
    action: BrevoApi.PutCorporateUserInvitationActionEmailRequestAction;
    /** Email address of the recipient */
    email: string;
}
