// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { toJson } from "../../../../core/json.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BrevoApi from "../../../index.js";

export declare namespace CompaniesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CompaniesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CompaniesClient.Options>;

    constructor(options: CompaniesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {BrevoApi.GetCompaniesRequest} request
     * @param {CompaniesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.companies.getAllCompanies()
     */
    public getAllCompanies(
        request: BrevoApi.GetCompaniesRequest = {},
        requestOptions?: CompaniesClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetCompaniesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getAllCompanies(request, requestOptions));
    }

    private async __getAllCompanies(
        request: BrevoApi.GetCompaniesRequest = {},
        requestOptions?: CompaniesClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetCompaniesResponse>> {
        const { filters, linkedContactsIds, linkedDealsIds, modifiedSince, createdSince, page, limit, sort, sortBy } =
            request;
        const _queryParams: Record<string, unknown> = {
            filters,
            linkedContactsIds,
            linkedDealsIds,
            modifiedSince,
            createdSince,
            page,
            limit,
            sort: sort != null ? sort : undefined,
            sortBy,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "companies",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetCompaniesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/companies");
    }

    /**
     * @param {BrevoApi.PostCompaniesRequest} request
     * @param {CompaniesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.companies.createACompany({
     *         name: "company"
     *     })
     */
    public createACompany(
        request: BrevoApi.PostCompaniesRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.PostCompaniesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createACompany(request, requestOptions));
    }

    private async __createACompany(
        request: BrevoApi.PostCompaniesRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.PostCompaniesResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "companies",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.PostCompaniesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/companies");
    }

    /**
     * Import companies from a CSV file with mapping options.
     *
     * @param {BrevoApi.PostCompaniesImportRequest} request
     * @param {CompaniesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     import { createReadStream } from "fs";
     *     await client.companies.importCompaniesCreationAndUpdation({})
     */
    public importCompaniesCreationAndUpdation(
        request: BrevoApi.PostCompaniesImportRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.PostCompaniesImportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__importCompaniesCreationAndUpdation(request, requestOptions));
    }

    private async __importCompaniesCreationAndUpdation(
        request: BrevoApi.PostCompaniesImportRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.PostCompaniesImportResponse>> {
        const _body = await core.newFormData();
        if (request.file != null) {
            await _body.appendFile("file", request.file);
        }

        if (request.mapping != null) {
            _body.append("mapping", toJson(request.mapping));
        }

        const _maybeEncodedRequest = await _body.getRequest();
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ..._maybeEncodedRequest.headers }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "companies/import",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            requestType: "file",
            duplex: _maybeEncodedRequest.duplex,
            body: _maybeEncodedRequest.body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.PostCompaniesImportResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/companies/import");
    }

    /**
     * @param {BrevoApi.PatchCompaniesLinkUnlinkIdRequest} request
     * @param {CompaniesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.companies.linkAndUnlinkCompanyWithContactAndDeal({
     *         id: "id"
     *     })
     */
    public linkAndUnlinkCompanyWithContactAndDeal(
        request: BrevoApi.PatchCompaniesLinkUnlinkIdRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(
            this.__linkAndUnlinkCompanyWithContactAndDeal(request, requestOptions),
        );
    }

    private async __linkAndUnlinkCompanyWithContactAndDeal(
        request: BrevoApi.PatchCompaniesLinkUnlinkIdRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `companies/link-unlink/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/companies/link-unlink/{id}");
    }

    /**
     * @param {BrevoApi.GetCompaniesIdRequest} request
     * @param {CompaniesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.companies.getACompany({
     *         id: "id"
     *     })
     */
    public getACompany(
        request: BrevoApi.GetCompaniesIdRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.Company> {
        return core.HttpResponsePromise.fromPromise(this.__getACompany(request, requestOptions));
    }

    private async __getACompany(
        request: BrevoApi.GetCompaniesIdRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.Company>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `companies/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.Company, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/companies/{id}");
    }

    /**
     * @param {BrevoApi.DeleteCompaniesIdRequest} request
     * @param {CompaniesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.companies.deleteACompany({
     *         id: "id"
     *     })
     */
    public deleteACompany(
        request: BrevoApi.DeleteCompaniesIdRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteACompany(request, requestOptions));
    }

    private async __deleteACompany(
        request: BrevoApi.DeleteCompaniesIdRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `companies/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/companies/{id}");
    }

    /**
     * @param {BrevoApi.PatchCompaniesIdRequest} request
     * @param {CompaniesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.companies.updateACompany({
     *         id: "id"
     *     })
     */
    public updateACompany(
        request: BrevoApi.PatchCompaniesIdRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.Company> {
        return core.HttpResponsePromise.fromPromise(this.__updateACompany(request, requestOptions));
    }

    private async __updateACompany(
        request: BrevoApi.PatchCompaniesIdRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.Company>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `companies/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.Company, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/companies/{id}");
    }

    /**
     * @param {BrevoApi.PostCrmAttributesRequest} request
     * @param {CompaniesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.companies.createACompanyDealAttribute({
     *         attributeType: "text",
     *         label: "Attribute Label",
     *         objectType: "companies"
     *     })
     */
    public createACompanyDealAttribute(
        request: BrevoApi.PostCrmAttributesRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.PostCrmAttributesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createACompanyDealAttribute(request, requestOptions));
    }

    private async __createACompanyDealAttribute(
        request: BrevoApi.PostCrmAttributesRequest,
        requestOptions?: CompaniesClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.PostCrmAttributesResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "crm/attributes",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.PostCrmAttributesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/crm/attributes");
    }

    /**
     * @param {CompaniesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.companies.getCompanyAttributes()
     */
    public getCompanyAttributes(
        requestOptions?: CompaniesClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetCrmAttributesCompaniesResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__getCompanyAttributes(requestOptions));
    }

    private async __getCompanyAttributes(
        requestOptions?: CompaniesClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetCrmAttributesCompaniesResponseItem[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "crm/attributes/companies",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetCrmAttributesCompaniesResponseItem[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.BrevoApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/crm/attributes/companies");
    }
}
