// This file was auto-generated by Fern from our API Definition.

import type * as BrevoApi from "../../../index.js";

export interface GetFolderListsResponse {
    /** Number of lists in the folder */
    count?: number | undefined;
    lists?: BrevoApi.GetList[] | undefined;
}
