// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BrevoApi from "../../../index.js";

export declare namespace BalanceClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BalanceClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BalanceClient.Options>;

    constructor(options: BalanceClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns Active Balances
     *
     * @param {BrevoApi.GetLoyaltyBalanceProgramsPidActiveBalanceRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.getActiveBalancesApi({
     *         pid: "pid",
     *         contact_id: 1,
     *         balance_definition_id: "balance_definition_id"
     *     })
     */
    public getActiveBalancesApi(
        request: BrevoApi.GetLoyaltyBalanceProgramsPidActiveBalanceRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.BalanceLimit> {
        return core.HttpResponsePromise.fromPromise(this.__getActiveBalancesApi(request, requestOptions));
    }

    private async __getActiveBalancesApi(
        request: BrevoApi.GetLoyaltyBalanceProgramsPidActiveBalanceRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.BalanceLimit>> {
        const {
            pid,
            limit,
            offset,
            sort_field: sortField,
            sort,
            contact_id: contactId,
            balance_definition_id: balanceDefinitionId,
        } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            sort_field: sortField,
            sort,
            contact_id: contactId,
            balance_definition_id: balanceDefinitionId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/active-balance`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.BalanceLimit, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/balance/programs/{pid}/active-balance",
        );
    }

    /**
     * Returns balance definition page
     *
     * @param {BrevoApi.GetBalanceDefinitionListRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.getBalanceDefinitionList({
     *         pid: "pid"
     *     })
     */
    public getBalanceDefinitionList(
        request: BrevoApi.GetBalanceDefinitionListRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetBalanceDefinitionListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getBalanceDefinitionList(request, requestOptions));
    }

    private async __getBalanceDefinitionList(
        request: BrevoApi.GetBalanceDefinitionListRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetBalanceDefinitionListResponse>> {
        const { pid, limit, offset, sortField, sort, version } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            sortField: sortField != null ? sortField : undefined,
            sort: sort != null ? sort : undefined,
            version: version != null ? version : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/balance-definitions`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetBalanceDefinitionListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/balance/programs/{pid}/balance-definitions",
        );
    }

    /**
     * Creates balance definition and returns information
     *
     * @param {BrevoApi.PostLoyaltyBalanceProgramsPidBalanceDefinitionsRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.createBalanceDefinition({
     *         pid: "pid",
     *         name: "name",
     *         unit: "POINTS"
     *     })
     */
    public createBalanceDefinition(
        request: BrevoApi.PostLoyaltyBalanceProgramsPidBalanceDefinitionsRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.BalanceDefinition> {
        return core.HttpResponsePromise.fromPromise(this.__createBalanceDefinition(request, requestOptions));
    }

    private async __createBalanceDefinition(
        request: BrevoApi.PostLoyaltyBalanceProgramsPidBalanceDefinitionsRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.BalanceDefinition>> {
        const { pid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/balance-definitions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.BalanceDefinition, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/balance/programs/{pid}/balance-definitions",
        );
    }

    /**
     * Returns balance definition
     *
     * @param {BrevoApi.GetBalanceDefinitionRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.getBalanceDefinition({
     *         pid: "pid",
     *         bdid: "bdid"
     *     })
     */
    public getBalanceDefinition(
        request: BrevoApi.GetBalanceDefinitionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.BalanceDefinition> {
        return core.HttpResponsePromise.fromPromise(this.__getBalanceDefinition(request, requestOptions));
    }

    private async __getBalanceDefinition(
        request: BrevoApi.GetBalanceDefinitionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.BalanceDefinition>> {
        const { pid, bdid, version } = request;
        const _queryParams: Record<string, unknown> = {
            version: version != null ? version : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/balance-definitions/${core.url.encodePathParam(bdid)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.BalanceDefinition, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/balance/programs/{pid}/balance-definitions/{bdid}",
        );
    }

    /**
     * Updates Balance definition
     *
     * @param {BrevoApi.UpdateBalanceDefinitionRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.FailedDependencyError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.updateBalanceDefinition({
     *         pid: "pid",
     *         bdid: "bdid",
     *         name: "name",
     *         unit: "POINTS"
     *     })
     */
    public updateBalanceDefinition(
        request: BrevoApi.UpdateBalanceDefinitionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.BalanceDefinition> {
        return core.HttpResponsePromise.fromPromise(this.__updateBalanceDefinition(request, requestOptions));
    }

    private async __updateBalanceDefinition(
        request: BrevoApi.UpdateBalanceDefinitionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.BalanceDefinition>> {
        const { pid, bdid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/balance-definitions/${core.url.encodePathParam(bdid)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.BalanceDefinition, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 424:
                    throw new BrevoApi.FailedDependencyError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/loyalty/balance/programs/{pid}/balance-definitions/{bdid}",
        );
    }

    /**
     * Delete Balance definition
     *
     * @param {BrevoApi.DeleteBalanceDefinitionRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.deleteBalanceDefinition({
     *         pid: "pid",
     *         bdid: "bdid"
     *     })
     */
    public deleteBalanceDefinition(
        request: BrevoApi.DeleteBalanceDefinitionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteBalanceDefinition(request, requestOptions));
    }

    private async __deleteBalanceDefinition(
        request: BrevoApi.DeleteBalanceDefinitionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { pid, bdid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/balance-definitions/${core.url.encodePathParam(bdid)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/loyalty/balance/programs/{pid}/balance-definitions/{bdid}",
        );
    }

    /**
     * Creates balance limit and sends the created UUID along with the data
     *
     * @param {BrevoApi.CreateBalanceLimitRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.FailedDependencyError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.createBalanceLimit({
     *         pid: "pid",
     *         bdid: "bdid",
     *         constraintType: "transaction",
     *         durationUnit: "day",
     *         durationValue: 1,
     *         transactionType: "credit",
     *         value: 1
     *     })
     */
    public createBalanceLimit(
        request: BrevoApi.CreateBalanceLimitRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.BalanceLimit> {
        return core.HttpResponsePromise.fromPromise(this.__createBalanceLimit(request, requestOptions));
    }

    private async __createBalanceLimit(
        request: BrevoApi.CreateBalanceLimitRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.BalanceLimit>> {
        const { pid, bdid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/balance-definitions/${core.url.encodePathParam(bdid)}/limits`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.BalanceLimit, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 424:
                    throw new BrevoApi.FailedDependencyError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/balance/programs/{pid}/balance-definitions/{bdid}/limits",
        );
    }

    /**
     * Fetches balance limits and send the created UUID along with the data
     *
     * @param {BrevoApi.GetBalanceLimitRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.getBalanceLimit({
     *         pid: "pid",
     *         bdid: "bdid",
     *         blid: "blid"
     *     })
     */
    public getBalanceLimit(
        request: BrevoApi.GetBalanceLimitRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.BalanceLimit> {
        return core.HttpResponsePromise.fromPromise(this.__getBalanceLimit(request, requestOptions));
    }

    private async __getBalanceLimit(
        request: BrevoApi.GetBalanceLimitRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.BalanceLimit>> {
        const { pid, bdid, blid, version } = request;
        const _queryParams: Record<string, unknown> = {
            version: version != null ? version : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/balance-definitions/${core.url.encodePathParam(bdid)}/limits/${core.url.encodePathParam(blid)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.BalanceLimit, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/balance/programs/{pid}/balance-definitions/{bdid}/limits/{blid}",
        );
    }

    /**
     * Updates balance limit
     *
     * @param {BrevoApi.UpdateBalanceLimitRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.updateBalanceLimit({
     *         pid: "pid",
     *         bdid: "bdid",
     *         blid: "blid",
     *         constraintType: "transaction",
     *         durationUnit: "day",
     *         durationValue: 1,
     *         transactionType: "credit",
     *         value: 1
     *     })
     */
    public updateBalanceLimit(
        request: BrevoApi.UpdateBalanceLimitRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.BalanceLimit> {
        return core.HttpResponsePromise.fromPromise(this.__updateBalanceLimit(request, requestOptions));
    }

    private async __updateBalanceLimit(
        request: BrevoApi.UpdateBalanceLimitRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.BalanceLimit>> {
        const { pid, bdid, blid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/balance-definitions/${core.url.encodePathParam(bdid)}/limits/${core.url.encodePathParam(blid)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.BalanceLimit, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/loyalty/balance/programs/{pid}/balance-definitions/{bdid}/limits/{blid}",
        );
    }

    /**
     * Delete balance limit
     *
     * @param {BrevoApi.DeleteBalanceLimitRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.deleteBalanceLimit({
     *         pid: "pid",
     *         bdid: "bdid",
     *         blid: "blid"
     *     })
     */
    public deleteBalanceLimit(
        request: BrevoApi.DeleteBalanceLimitRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteBalanceLimit(request, requestOptions));
    }

    private async __deleteBalanceLimit(
        request: BrevoApi.DeleteBalanceLimitRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { pid, bdid, blid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/balance-definitions/${core.url.encodePathParam(bdid)}/limits/${core.url.encodePathParam(blid)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/loyalty/balance/programs/{pid}/balance-definitions/{bdid}/limits/{blid}",
        );
    }

    /**
     * Returns balance list
     *
     * @param {BrevoApi.GetContactBalancesRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.getContactBalances({
     *         pid: "pid"
     *     })
     */
    public getContactBalances(
        request: BrevoApi.GetContactBalancesRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetContactBalancesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getContactBalances(request, requestOptions));
    }

    private async __getContactBalances(
        request: BrevoApi.GetContactBalancesRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetContactBalancesResponse>> {
        const { pid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/contact-balances`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetContactBalancesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/balance/programs/{pid}/contact-balances",
        );
    }

    /**
     * Returns created order
     *
     * @param {BrevoApi.CreateBalanceOrderRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.createBalanceOrder({
     *         pid: "pid",
     *         amount: 1.1,
     *         balanceDefinitionId: "balanceDefinitionId",
     *         contactId: 1,
     *         dueAt: "dueAt",
     *         source: "source"
     *     })
     */
    public createBalanceOrder(
        request: BrevoApi.CreateBalanceOrderRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.CreateBalanceOrderResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createBalanceOrder(request, requestOptions));
    }

    private async __createBalanceOrder(
        request: BrevoApi.CreateBalanceOrderRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.CreateBalanceOrderResponse>> {
        const { pid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/create-order`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.CreateBalanceOrderResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/balance/programs/{pid}/create-order",
        );
    }

    /**
     * Returns subscription balances
     *
     * @param {BrevoApi.GetSubscriptionBalancesRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.getSubscriptionBalances({
     *         pid: "pid",
     *         cid: "cid"
     *     })
     */
    public getSubscriptionBalances(
        request: BrevoApi.GetSubscriptionBalancesRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetSubscriptionBalancesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSubscriptionBalances(request, requestOptions));
    }

    private async __getSubscriptionBalances(
        request: BrevoApi.GetSubscriptionBalancesRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetSubscriptionBalancesResponse>> {
        const { pid, cid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/subscriptions/${core.url.encodePathParam(cid)}/balances`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetSubscriptionBalancesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/balance/programs/{pid}/subscriptions/{cid}/balances",
        );
    }

    /**
     * Creates a balance for a contact
     *
     * @param {BrevoApi.PostLoyaltyBalanceProgramsPidSubscriptionsCidBalancesRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.createSubscriptionBalances({
     *         pid: "pid",
     *         cid: "cid",
     *         balanceDefinitionId: "balanceDefinitionId"
     *     })
     */
    public createSubscriptionBalances(
        request: BrevoApi.PostLoyaltyBalanceProgramsPidSubscriptionsCidBalancesRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.PostLoyaltyBalanceProgramsPidSubscriptionsCidBalancesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createSubscriptionBalances(request, requestOptions));
    }

    private async __createSubscriptionBalances(
        request: BrevoApi.PostLoyaltyBalanceProgramsPidSubscriptionsCidBalancesRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.PostLoyaltyBalanceProgramsPidSubscriptionsCidBalancesResponse>> {
        const { pid, cid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/subscriptions/${core.url.encodePathParam(cid)}/balances`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.PostLoyaltyBalanceProgramsPidSubscriptionsCidBalancesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/balance/programs/{pid}/subscriptions/{cid}/balances",
        );
    }

    /**
     * Returns transaction history
     *
     * @param {BrevoApi.GetLoyaltyBalanceProgramsPidTransactionHistoryRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.getTransactionHistoryApi({
     *         pid: "pid",
     *         contact_id: 1,
     *         balance_definition_id: "balance_definition_id"
     *     })
     */
    public getTransactionHistoryApi(
        request: BrevoApi.GetLoyaltyBalanceProgramsPidTransactionHistoryRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetLoyaltyBalanceProgramsPidTransactionHistoryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTransactionHistoryApi(request, requestOptions));
    }

    private async __getTransactionHistoryApi(
        request: BrevoApi.GetLoyaltyBalanceProgramsPidTransactionHistoryRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetLoyaltyBalanceProgramsPidTransactionHistoryResponse>> {
        const {
            pid,
            limit,
            offset,
            sort_field: sortField,
            sort,
            contact_id: contactId,
            balance_definition_id: balanceDefinitionId,
            filters,
        } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            sort_field: sortField != null ? sortField : undefined,
            sort: sort != null ? sort : undefined,
            contact_id: contactId,
            balance_definition_id: balanceDefinitionId,
            filters,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/transaction-history`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetLoyaltyBalanceProgramsPidTransactionHistoryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/loyalty/balance/programs/{pid}/transaction-history",
        );
    }

    /**
     * Creates new transaction and returns information
     *
     * @param {BrevoApi.BeginTransactionRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.beginTransaction({
     *         pid: "pid",
     *         amount: 1.1,
     *         balanceDefinitionId: "balanceDefinitionId"
     *     })
     */
    public beginTransaction(
        request: BrevoApi.BeginTransactionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.Transaction> {
        return core.HttpResponsePromise.fromPromise(this.__beginTransaction(request, requestOptions));
    }

    private async __beginTransaction(
        request: BrevoApi.BeginTransactionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.Transaction>> {
        const { pid, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/transactions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.Transaction, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/balance/programs/{pid}/transactions",
        );
    }

    /**
     * Cancels transaction
     *
     * @param {BrevoApi.CancelTransactionRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.cancelTransaction({
     *         pid: "pid",
     *         tid: "tid"
     *     })
     */
    public cancelTransaction(
        request: BrevoApi.CancelTransactionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.Transaction> {
        return core.HttpResponsePromise.fromPromise(this.__cancelTransaction(request, requestOptions));
    }

    private async __cancelTransaction(
        request: BrevoApi.CancelTransactionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.Transaction>> {
        const { pid, tid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/transactions/${core.url.encodePathParam(tid)}/cancel`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.Transaction, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/balance/programs/{pid}/transactions/{tid}/cancel",
        );
    }

    /**
     * Completes transaction
     *
     * @param {BrevoApi.CompleteTransactionRequest} request
     * @param {BalanceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     * @throws {@link BrevoApi.InternalServerError}
     *
     * @example
     *     await client.balance.completeTransaction({
     *         pid: "pid",
     *         tid: "tid"
     *     })
     */
    public completeTransaction(
        request: BrevoApi.CompleteTransactionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.Transaction> {
        return core.HttpResponsePromise.fromPromise(this.__completeTransaction(request, requestOptions));
    }

    private async __completeTransaction(
        request: BrevoApi.CompleteTransactionRequest,
        requestOptions?: BalanceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.Transaction>> {
        const { pid, tid } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `loyalty/balance/programs/${core.url.encodePathParam(pid)}/transactions/${core.url.encodePathParam(tid)}/complete`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.Transaction, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrevoApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/loyalty/balance/programs/{pid}/transactions/{tid}/complete",
        );
    }
}
