// This file was auto-generated by Fern from our API Definition.

import type * as BrevoApi from "../../../../index.js";

/**
 * @example
 *     {
 *         action: "resend",
 *         email: "email"
 *     }
 */
export interface PutresendcancelinvitationRequest {
    /** action */
    action: BrevoApi.PutresendcancelinvitationRequestAction;
    /** Email of the invited user. */
    email: string;
}
