// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BrevoApi from "../../../index.js";

export declare namespace EcommerceClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class EcommerceClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EcommerceClient.Options>;

    constructor(options: EcommerceClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {BrevoApi.GetCategoriesRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.getCategories()
     */
    public getCategories(
        request: BrevoApi.GetCategoriesRequest = {},
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetCategoriesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getCategories(request, requestOptions));
    }

    private async __getCategories(
        request: BrevoApi.GetCategoriesRequest = {},
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetCategoriesResponse>> {
        const { limit, offset, sort, ids, name, modifiedSince, createdSince, isDeleted } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            sort: sort != null ? sort : undefined,
            ids,
            name,
            modifiedSince,
            createdSince,
            isDeleted,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "categories",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetCategoriesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/categories");
    }

    /**
     * @param {BrevoApi.CreateUpdateCategoryRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.createUpdateCategory({
     *         id: "CAT123"
     *     })
     */
    public createUpdateCategory(
        request: BrevoApi.CreateUpdateCategoryRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.CreateUpdateCategoryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createUpdateCategory(request, requestOptions));
    }

    private async __createUpdateCategory(
        request: BrevoApi.CreateUpdateCategoryRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.CreateUpdateCategoryResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "categories",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.CreateUpdateCategoryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/categories");
    }

    /**
     * @param {BrevoApi.CreateUpdateBatchCategoryRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.createUpdateBatchCategory({
     *         categories: [{
     *                 id: "CAT123"
     *             }]
     *     })
     */
    public createUpdateBatchCategory(
        request: BrevoApi.CreateUpdateBatchCategoryRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.CreateUpdateBatchCategoryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createUpdateBatchCategory(request, requestOptions));
    }

    private async __createUpdateBatchCategory(
        request: BrevoApi.CreateUpdateBatchCategoryRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.CreateUpdateBatchCategoryResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "categories/batch",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.CreateUpdateBatchCategoryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/categories/batch");
    }

    /**
     * @param {BrevoApi.GetCategoryInfoRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.ecommerce.getCategoryInfo({
     *         id: "id"
     *     })
     */
    public getCategoryInfo(
        request: BrevoApi.GetCategoryInfoRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetCategoryDetails> {
        return core.HttpResponsePromise.fromPromise(this.__getCategoryInfo(request, requestOptions));
    }

    private async __getCategoryInfo(
        request: BrevoApi.GetCategoryInfoRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetCategoryDetails>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `categories/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetCategoryDetails, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/categories/{id}");
    }

    /**
     * Getting access to Brevo eCommerce.
     *
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.ecommerce.activateTheECommerceApp()
     */
    public activateTheECommerceApp(requestOptions?: EcommerceClient.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__activateTheECommerceApp(requestOptions));
    }

    private async __activateTheECommerceApp(
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "ecommerce/activate",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/ecommerce/activate");
    }

    /**
     * @param {BrevoApi.GetEcommerceAttributionMetricsRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.getAttributionMetricsForOneOrMoreBrevoCampaignsOrWorkflows({
     *         periodFrom: "2022-01-02T00:00:00Z",
     *         periodTo: "2022-01-03T00:00:00Z"
     *     })
     */
    public getAttributionMetricsForOneOrMoreBrevoCampaignsOrWorkflows(
        request: BrevoApi.GetEcommerceAttributionMetricsRequest = {},
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetEcommerceAttributionMetricsResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__getAttributionMetricsForOneOrMoreBrevoCampaignsOrWorkflows(request, requestOptions),
        );
    }

    private async __getAttributionMetricsForOneOrMoreBrevoCampaignsOrWorkflows(
        request: BrevoApi.GetEcommerceAttributionMetricsRequest = {},
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetEcommerceAttributionMetricsResponse>> {
        const {
            periodFrom,
            periodTo,
            "emailCampaignId[]": emailCampaignIdArray,
            "smsCampaignId[]": smsCampaignIdArray,
            "automationWorkflowEmailId[]": automationWorkflowEmailIdArray,
            "automationWorkflowSmsId[]": automationWorkflowSmsIdArray,
        } = request;
        const _queryParams: Record<string, unknown> = {
            periodFrom: periodFrom != null ? periodFrom : undefined,
            periodTo: periodTo != null ? periodTo : undefined,
            "emailCampaignId[]": emailCampaignIdArray,
            "smsCampaignId[]": smsCampaignIdArray,
            "automationWorkflowEmailId[]": automationWorkflowEmailIdArray,
            "automationWorkflowSmsId[]": automationWorkflowSmsIdArray,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "ecommerce/attribution/metrics",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetEcommerceAttributionMetricsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/ecommerce/attribution/metrics",
        );
    }

    /**
     * @param {BrevoApi.GetEcommerceAttributionMetricsConversionSourceConversionSourceIdRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.getDetailedAttributionMetricsForASingleBrevoCampaignOrWorkflow({
     *         conversionSource: "email_campaign",
     *         conversionSourceId: "sale"
     *     })
     */
    public getDetailedAttributionMetricsForASingleBrevoCampaignOrWorkflow(
        request: BrevoApi.GetEcommerceAttributionMetricsConversionSourceConversionSourceIdRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetEcommerceAttributionMetricsConversionSourceConversionSourceIdResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__getDetailedAttributionMetricsForASingleBrevoCampaignOrWorkflow(request, requestOptions),
        );
    }

    private async __getDetailedAttributionMetricsForASingleBrevoCampaignOrWorkflow(
        request: BrevoApi.GetEcommerceAttributionMetricsConversionSourceConversionSourceIdRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<BrevoApi.GetEcommerceAttributionMetricsConversionSourceConversionSourceIdResponse>
    > {
        const { conversionSource, conversionSourceId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `ecommerce/attribution/metrics/${core.url.encodePathParam(conversionSource)}/${core.url.encodePathParam(conversionSourceId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetEcommerceAttributionMetricsConversionSourceConversionSourceIdResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/ecommerce/attribution/metrics/{conversionSource}/{conversionSourceId}",
        );
    }

    /**
     * @param {BrevoApi.GetEcommerceAttributionProductsConversionSourceConversionSourceIdRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.getAttributedProductSalesForASingleBrevoCampaignOrWorkflow({
     *         conversionSource: "email_campaign",
     *         conversionSourceId: "sale"
     *     })
     */
    public getAttributedProductSalesForASingleBrevoCampaignOrWorkflow(
        request: BrevoApi.GetEcommerceAttributionProductsConversionSourceConversionSourceIdRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetEcommerceAttributionProductsConversionSourceConversionSourceIdResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__getAttributedProductSalesForASingleBrevoCampaignOrWorkflow(request, requestOptions),
        );
    }

    private async __getAttributedProductSalesForASingleBrevoCampaignOrWorkflow(
        request: BrevoApi.GetEcommerceAttributionProductsConversionSourceConversionSourceIdRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<
        core.WithRawResponse<BrevoApi.GetEcommerceAttributionProductsConversionSourceConversionSourceIdResponse>
    > {
        const { conversionSource, conversionSourceId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `ecommerce/attribution/products/${core.url.encodePathParam(conversionSource)}/${core.url.encodePathParam(conversionSourceId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetEcommerceAttributionProductsConversionSourceConversionSourceIdResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/ecommerce/attribution/products/{conversionSource}/{conversionSourceId}",
        );
    }

    /**
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     *
     * @example
     *     await client.ecommerce.getTheIso4217CompliantDisplayCurrencyCodeForYourBrevoAccount()
     */
    public getTheIso4217CompliantDisplayCurrencyCodeForYourBrevoAccount(
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetEcommerceConfigDisplayCurrencyResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__getTheIso4217CompliantDisplayCurrencyCodeForYourBrevoAccount(requestOptions),
        );
    }

    private async __getTheIso4217CompliantDisplayCurrencyCodeForYourBrevoAccount(
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetEcommerceConfigDisplayCurrencyResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "ecommerce/config/displayCurrency",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.GetEcommerceConfigDisplayCurrencyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/ecommerce/config/displayCurrency",
        );
    }

    /**
     * @param {BrevoApi.SetConfigDisplayCurrencyRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.UnprocessableEntityError}
     *
     * @example
     *     await client.ecommerce.setConfigDisplayCurrency({
     *         code: "EUR"
     *     })
     */
    public setConfigDisplayCurrency(
        request: BrevoApi.SetConfigDisplayCurrencyRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.SetConfigDisplayCurrencyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__setConfigDisplayCurrency(request, requestOptions));
    }

    private async __setConfigDisplayCurrency(
        request: BrevoApi.SetConfigDisplayCurrencyRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.SetConfigDisplayCurrencyResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "ecommerce/config/displayCurrency",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.SetConfigDisplayCurrencyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrevoApi.UnprocessableEntityError(
                        _response.error.body as BrevoApi.ErrorModel,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/ecommerce/config/displayCurrency",
        );
    }

    /**
     * Get all the orders
     *
     * @param {BrevoApi.GetOrdersRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.getOrders()
     */
    public getOrders(
        request: BrevoApi.GetOrdersRequest = {},
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getOrders(request, requestOptions));
    }

    private async __getOrders(
        request: BrevoApi.GetOrdersRequest = {},
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { limit, offset, sort, modifiedSince, createdSince } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            sort: sort != null ? sort : undefined,
            modifiedSince,
            createdSince,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "orders",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/orders");
    }

    /**
     * Manages the transactional status of the order
     *
     * @param {BrevoApi.Order} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.createOrder({
     *         amount: 308.42,
     *         createdAt: "2021-07-29T20:59:23.383Z",
     *         id: "14",
     *         products: [{
     *                 price: 99.99,
     *                 productId: "P1",
     *                 quantity: 10
     *             }],
     *         status: "completed",
     *         updatedAt: "2021-07-30T10:59:23.383Z"
     *     })
     */
    public createOrder(
        request: BrevoApi.Order,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__createOrder(request, requestOptions));
    }

    private async __createOrder(
        request: BrevoApi.Order,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "orders/status",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/orders/status");
    }

    /**
     * Create multiple orders at one time instead of one order at a time
     *
     * @param {BrevoApi.CreateBatchOrderRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.createBatchOrder({
     *         orders: [{
     *                 amount: 308.42,
     *                 createdAt: "2021-07-29T20:59:23.383Z",
     *                 id: "14",
     *                 products: [{
     *                         price: 99.99,
     *                         productId: "P1",
     *                         quantity: 10
     *                     }],
     *                 status: "completed",
     *                 updatedAt: "2021-07-30T10:59:23.383Z"
     *             }]
     *     })
     */
    public createBatchOrder(
        request: BrevoApi.CreateBatchOrderRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.CreateBatchOrderResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createBatchOrder(request, requestOptions));
    }

    private async __createBatchOrder(
        request: BrevoApi.CreateBatchOrderRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.CreateBatchOrderResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "orders/status/batch",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.CreateBatchOrderResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/orders/status/batch");
    }

    /**
     * @param {BrevoApi.GetProductsRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.getProducts()
     */
    public getProducts(
        request: BrevoApi.GetProductsRequest = {},
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetProductsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getProducts(request, requestOptions));
    }

    private async __getProducts(
        request: BrevoApi.GetProductsRequest = {},
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetProductsResponse>> {
        const {
            limit,
            offset,
            sort,
            ids,
            name,
            "price[lte]": priceLte,
            "price[gte]": priceGte,
            "price[lt]": priceLt,
            "price[gt]": priceGt,
            "price[eq]": priceEq,
            "price[ne]": priceNe,
            categories,
            modifiedSince,
            createdSince,
            isDeleted,
        } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            offset,
            sort: sort != null ? sort : undefined,
            ids,
            name,
            "price[lte]": priceLte,
            "price[gte]": priceGte,
            "price[lt]": priceLt,
            "price[gt]": priceGt,
            "price[eq]": priceEq,
            "price[ne]": priceNe,
            categories,
            modifiedSince,
            createdSince,
            isDeleted,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "products",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetProductsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/products");
    }

    /**
     * @param {BrevoApi.CreateUpdateProductRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.createUpdateProduct({
     *         id: "P11",
     *         name: "Iphone 11"
     *     })
     */
    public createUpdateProduct(
        request: BrevoApi.CreateUpdateProductRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.CreateUpdateProductResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createUpdateProduct(request, requestOptions));
    }

    private async __createUpdateProduct(
        request: BrevoApi.CreateUpdateProductRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.CreateUpdateProductResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "products",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.CreateUpdateProductResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/products");
    }

    /**
     * @param {BrevoApi.CreateUpdateBatchProductsRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     *
     * @example
     *     await client.ecommerce.createUpdateBatchProducts({
     *         products: [{
     *                 id: "P11",
     *                 name: "Iphone 11"
     *             }]
     *     })
     */
    public createUpdateBatchProducts(
        request: BrevoApi.CreateUpdateBatchProductsRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.CreateUpdateBatchProductsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createUpdateBatchProducts(request, requestOptions));
    }

    private async __createUpdateBatchProducts(
        request: BrevoApi.CreateUpdateBatchProductsRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.CreateUpdateBatchProductsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                "products/batch",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrevoApi.CreateUpdateBatchProductsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/products/batch");
    }

    /**
     * @param {BrevoApi.GetProductInfoRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.ecommerce.getProductInfo({
     *         id: "id"
     *     })
     */
    public getProductInfo(
        request: BrevoApi.GetProductInfoRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<BrevoApi.GetProductDetails> {
        return core.HttpResponsePromise.fromPromise(this.__getProductInfo(request, requestOptions));
    }

    private async __getProductInfo(
        request: BrevoApi.GetProductInfoRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<BrevoApi.GetProductDetails>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `products/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrevoApi.GetProductDetails, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/products/{id}");
    }

    /**
     * @param {BrevoApi.CreateProductAlertRequest} request
     * @param {EcommerceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrevoApi.BadRequestError}
     * @throws {@link BrevoApi.UnauthorizedError}
     * @throws {@link BrevoApi.ForbiddenError}
     * @throws {@link BrevoApi.NotFoundError}
     *
     * @example
     *     await client.ecommerce.createProductAlert({
     *         id: "id",
     *         type: "back_in_stock"
     *     })
     */
    public createProductAlert(
        request: BrevoApi.CreateProductAlertRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__createProductAlert(request, requestOptions));
    }

    private async __createProductAlert(
        request: BrevoApi.CreateProductAlertRequest,
        requestOptions?: EcommerceClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id, type: type_, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrevoApiEnvironment.Default,
                `products/${core.url.encodePathParam(id)}/alerts/${core.url.encodePathParam(type_)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrevoApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new BrevoApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new BrevoApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrevoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrevoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/products/{id}/alerts/{type}");
    }
}
