# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetParameterSubscriptionInfoResponseBalanceBalancesItem(UniversalBaseModel):
    balance_definition_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="balanceDefinitionId"),
        pydantic.Field(alias="balanceDefinitionId", description="Unique identifier for the balance definition)."),
    ] = None
    value: typing.Optional[float] = pydantic.Field(default=None)
    """
    The amount of the balance.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
