// This file was auto-generated by Fern from our API Definition.

import type * as BrevoApi from "../index.js";

export interface NodeResponse {
    /** array[object] */
    args?: BrevoApi.NodeResponse[] | undefined;
    /** Array values for rule definition */
    array?: BrevoApi.NodeResponse[] | undefined;
    /** Boolean values for rule definition */
    boolean?: boolean | undefined;
    /** Description for rule definition */
    description?: string | undefined;
    /** Float values for rule definition */
    float?: number | undefined;
    /** int64 */
    int?: number | undefined;
    /** Operator selected for rule definition */
    op?: string | undefined;
    /** Boolean values for rule definition */
    string?: string | undefined;
}
