// This file was auto-generated by Fern from our API Definition.

import type * as BrevoApi from "../index.js";

export interface RuleConditionResponse {
    /** Metric to indicate AND between rules */
    and?: BrevoApi.RuleConditionResponse[] | undefined;
    /** Condition of the rule */
    lhs?: BrevoApi.ValueResponse | undefined;
    /** Selected operator for the rule */
    op?: string | undefined;
    /** Metric to indicate OR between rules */
    or?: BrevoApi.RuleConditionResponse[] | undefined;
    /** Action of the rule */
    rhs?: BrevoApi.ValueResponse | undefined;
}
