// This file was auto-generated by Fern from our API Definition.

import type * as BrevoApi from "../index.js";

export interface ValueResponse {
    /** Array values to define the rule */
    array?: BrevoApi.ValueResponse[] | undefined;
    /** Boolean values for rule definition */
    boolean?: boolean | undefined;
    /** string */
    contactProperty?: string | undefined;
    /** Selected date for rule definition */
    date?: string | undefined;
    /** Selected event property for rule definition */
    eventProperty?: string | undefined;
    /** Created expression for rule definition */
    expression?: BrevoApi.NodeResponse | undefined;
    /** Boolean values for rule definition */
    number?: number | undefined;
    /** String values for rule definition */
    string?: string | undefined;
}
