# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_segments_response_segments_item import GetSegmentsResponseSegmentsItem


class GetSegmentsResponse(UniversalBaseModel):
    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of Segments in your account
    """

    segments: typing.Optional[typing.List[GetSegmentsResponseSegmentsItem]] = pydantic.Field(default=None)
    """
    Listing of all the segments available in your account
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
