// This file was auto-generated by Fern from our API Definition.

import * as BrevoApi from "../../src/api/index";
import { BrevoApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TierClient", () => {
    test("addSubscriptionToTier (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            contactId: 1,
            createdAt: "2024-01-15T09:30:00Z",
            groupId: "groupId",
            id: "id",
            loyaltyProgramId: "loyaltyProgramId",
            meta: { key: "value" },
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/contacts/cid/tiers/tid")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tier.addSubscriptionToTier({
            pid: "pid",
            cid: "cid",
            tid: "tid",
        });
        expect(response).toEqual({
            contactId: 1,
            createdAt: "2024-01-15T09:30:00Z",
            groupId: "groupId",
            id: "id",
            loyaltyProgramId: "loyaltyProgramId",
            meta: {
                key: "value",
            },
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("addSubscriptionToTier (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/contacts/cid/tiers/tid")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.addSubscriptionToTier({
                pid: "pid",
                cid: "cid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("addSubscriptionToTier (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/contacts/cid/tiers/tid")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.addSubscriptionToTier({
                pid: "pid",
                cid: "cid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("addSubscriptionToTier (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/contacts/cid/tiers/tid")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.addSubscriptionToTier({
                pid: "pid",
                cid: "cid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("addSubscriptionToTier (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/contacts/cid/tiers/tid")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.addSubscriptionToTier({
                pid: "pid",
                cid: "cid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.ConflictError);
    });

    test("addSubscriptionToTier (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/contacts/cid/tiers/tid")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.addSubscriptionToTier({
                pid: "pid",
                cid: "cid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("addSubscriptionToTier (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/contacts/cid/tiers/tid")
            .respondWith()
            .statusCode(424)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.addSubscriptionToTier({
                pid: "pid",
                cid: "cid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.FailedDependencyError);
    });

    test("addSubscriptionToTier (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/contacts/cid/tiers/tid")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.addSubscriptionToTier({
                pid: "pid",
                cid: "cid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.InternalServerError);
    });

    test("getListOfTierGroups (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    createdAt: "2024-01-15T09:30:00Z",
                    downgradeStrategy: "real_time",
                    id: "id",
                    loyaltyProgramId: "loyaltyProgramId",
                    name: "name",
                    tierOrder: ["tierOrder"],
                    updatedAt: "2024-01-15T09:30:00Z",
                    upgradeStrategy: "real_time",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tier.getListOfTierGroups({
            pid: "pid",
        });
        expect(response).toEqual({
            items: [
                {
                    createdAt: "2024-01-15T09:30:00Z",
                    downgradeStrategy: "real_time",
                    id: "id",
                    loyaltyProgramId: "loyaltyProgramId",
                    name: "name",
                    tierOrder: ["tierOrder"],
                    updatedAt: "2024-01-15T09:30:00Z",
                    upgradeStrategy: "real_time",
                },
            ],
        });
    });

    test("getListOfTierGroups (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getListOfTierGroups({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("getListOfTierGroups (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getListOfTierGroups({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("getListOfTierGroups (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getListOfTierGroups({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("getListOfTierGroups (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getListOfTierGroups({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("getListOfTierGroups (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getListOfTierGroups({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.InternalServerError);
    });

    test("createTierGroup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            createdAt: "2024-01-15T09:30:00Z",
            downgradeStrategy: "real_time",
            id: "id",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierOrder: ["tierOrder"],
            updatedAt: "2024-01-15T09:30:00Z",
            upgradeStrategy: "real_time",
        };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tier.createTierGroup({
            pid: "pid",
            name: "name",
        });
        expect(response).toEqual({
            createdAt: "2024-01-15T09:30:00Z",
            downgradeStrategy: "real_time",
            id: "id",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierOrder: ["tierOrder"],
            updatedAt: "2024-01-15T09:30:00Z",
            upgradeStrategy: "real_time",
        });
    });

    test("createTierGroup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierGroup({
                pid: "pid",
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.BadRequestError);
    });

    test("createTierGroup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierGroup({
                pid: "pid",
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("createTierGroup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierGroup({
                pid: "pid",
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("createTierGroup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierGroup({
                pid: "pid",
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("createTierGroup (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierGroup({
                pid: "pid",
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.ConflictError);
    });

    test("createTierGroup (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierGroup({
                pid: "pid",
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("getTierGroup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            createdAt: "2024-01-15T09:30:00Z",
            downgradeStrategy: "real_time",
            id: "id",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierOrder: ["tierOrder"],
            updatedAt: "2024-01-15T09:30:00Z",
            upgradeStrategy: "real_time",
        };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tier.getTierGroup({
            pid: "pid",
            gid: "gid",
        });
        expect(response).toEqual({
            createdAt: "2024-01-15T09:30:00Z",
            downgradeStrategy: "real_time",
            id: "id",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierOrder: ["tierOrder"],
            updatedAt: "2024-01-15T09:30:00Z",
            upgradeStrategy: "real_time",
        });
    });

    test("getTierGroup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("getTierGroup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("getTierGroup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("getTierGroup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("getTierGroup (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.InternalServerError);
    });

    test("updateTierGroup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            downgradeStrategy: "real_time",
            name: "name",
            tierOrder: ["tierOrder"],
            upgradeStrategy: "real_time",
        };
        const rawResponseBody = {
            createdAt: "2024-01-15T09:30:00Z",
            downgradeStrategy: "real_time",
            id: "id",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierOrder: ["tierOrder"],
            updatedAt: "2024-01-15T09:30:00Z",
            upgradeStrategy: "real_time",
        };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tier-groups/gid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tier.updateTierGroup({
            pid: "pid",
            gid: "gid",
            downgradeStrategy: "real_time",
            name: "name",
            tierOrder: ["tierOrder"],
            upgradeStrategy: "real_time",
        });
        expect(response).toEqual({
            createdAt: "2024-01-15T09:30:00Z",
            downgradeStrategy: "real_time",
            id: "id",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierOrder: ["tierOrder"],
            updatedAt: "2024-01-15T09:30:00Z",
            upgradeStrategy: "real_time",
        });
    });

    test("updateTierGroup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            downgradeStrategy: "real_time",
            name: "name",
            tierOrder: ["tierOrder", "tierOrder"],
            upgradeStrategy: "real_time",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tier-groups/gid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTierGroup({
                pid: "pid",
                gid: "gid",
                downgradeStrategy: "real_time",
                name: "name",
                tierOrder: ["tierOrder", "tierOrder"],
                upgradeStrategy: "real_time",
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("updateTierGroup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            downgradeStrategy: "real_time",
            name: "name",
            tierOrder: ["tierOrder", "tierOrder"],
            upgradeStrategy: "real_time",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tier-groups/gid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTierGroup({
                pid: "pid",
                gid: "gid",
                downgradeStrategy: "real_time",
                name: "name",
                tierOrder: ["tierOrder", "tierOrder"],
                upgradeStrategy: "real_time",
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("updateTierGroup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            downgradeStrategy: "real_time",
            name: "name",
            tierOrder: ["tierOrder", "tierOrder"],
            upgradeStrategy: "real_time",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tier-groups/gid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTierGroup({
                pid: "pid",
                gid: "gid",
                downgradeStrategy: "real_time",
                name: "name",
                tierOrder: ["tierOrder", "tierOrder"],
                upgradeStrategy: "real_time",
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("updateTierGroup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            downgradeStrategy: "real_time",
            name: "name",
            tierOrder: ["tierOrder", "tierOrder"],
            upgradeStrategy: "real_time",
        };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tier-groups/gid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTierGroup({
                pid: "pid",
                gid: "gid",
                downgradeStrategy: "real_time",
                name: "name",
                tierOrder: ["tierOrder", "tierOrder"],
                upgradeStrategy: "real_time",
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("updateTierGroup (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            downgradeStrategy: "real_time",
            name: "name",
            tierOrder: ["tierOrder", "tierOrder"],
            upgradeStrategy: "real_time",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tier-groups/gid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTierGroup({
                pid: "pid",
                gid: "gid",
                downgradeStrategy: "real_time",
                name: "name",
                tierOrder: ["tierOrder", "tierOrder"],
                upgradeStrategy: "real_time",
            });
        }).rejects.toThrow(BrevoApi.InternalServerError);
    });

    test("deleteTierGroup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.tier.deleteTierGroup({
            pid: "pid",
            gid: "gid",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteTierGroup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("deleteTierGroup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("deleteTierGroup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("deleteTierGroup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.ConflictError);
    });

    test("deleteTierGroup (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("deleteTierGroup (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tier-groups/gid")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTierGroup({
                pid: "pid",
                gid: "gid",
            });
        }).rejects.toThrow(BrevoApi.InternalServerError);
    });

    test("createTierForTierGroup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}], name: "name" };
        const rawResponseBody = {
            accessConditions: [
                {
                    balanceDefinitionId: "balanceDefinitionId",
                    createdAt: "2024-01-15T09:30:00Z",
                    minimumValue: 1,
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            createdAt: "2024-01-15T09:30:00Z",
            groupId: "groupId",
            imageRef: "imageRef",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierId: "tierId",
            tierRewards: [
                { createdAt: "2024-01-15T09:30:00Z", rewardId: "rewardId", updatedAt: "2024-01-15T09:30:00Z" },
            ],
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups/gid/tiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tier.createTierForTierGroup({
            pid: "pid",
            gid: "gid",
            accessConditions: [{}],
            name: "name",
        });
        expect(response).toEqual({
            accessConditions: [
                {
                    balanceDefinitionId: "balanceDefinitionId",
                    createdAt: "2024-01-15T09:30:00Z",
                    minimumValue: 1,
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            createdAt: "2024-01-15T09:30:00Z",
            groupId: "groupId",
            imageRef: "imageRef",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierId: "tierId",
            tierRewards: [
                {
                    createdAt: "2024-01-15T09:30:00Z",
                    rewardId: "rewardId",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("createTierForTierGroup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups/gid/tiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierForTierGroup({
                pid: "pid",
                gid: "gid",
                accessConditions: [{}, {}],
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("createTierForTierGroup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups/gid/tiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierForTierGroup({
                pid: "pid",
                gid: "gid",
                accessConditions: [{}, {}],
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("createTierForTierGroup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups/gid/tiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierForTierGroup({
                pid: "pid",
                gid: "gid",
                accessConditions: [{}, {}],
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("createTierForTierGroup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name" };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups/gid/tiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierForTierGroup({
                pid: "pid",
                gid: "gid",
                accessConditions: [{}, {}],
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("createTierForTierGroup (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/loyalty/tier/programs/pid/tier-groups/gid/tiers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.createTierForTierGroup({
                pid: "pid",
                gid: "gid",
                accessConditions: [{}, {}],
                name: "name",
            });
        }).rejects.toThrow(BrevoApi.InternalServerError);
    });

    test("getLoyaltyProgramTier (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    accessConditions: [{}],
                    createdAt: "2024-01-15T09:30:00Z",
                    groupId: "groupId",
                    imageRef: "imageRef",
                    loyaltyProgramId: "loyaltyProgramId",
                    name: "name",
                    tierId: "tierId",
                    tierRewards: [{}],
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tiers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tier.getLoyaltyProgramTier({
            pid: "pid",
        });
        expect(response).toEqual({
            items: [
                {
                    accessConditions: [{}],
                    createdAt: "2024-01-15T09:30:00Z",
                    groupId: "groupId",
                    imageRef: "imageRef",
                    loyaltyProgramId: "loyaltyProgramId",
                    name: "name",
                    tierId: "tierId",
                    tierRewards: [{}],
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        });
    });

    test("getLoyaltyProgramTier (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tiers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getLoyaltyProgramTier({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("getLoyaltyProgramTier (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tiers")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getLoyaltyProgramTier({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("getLoyaltyProgramTier (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tiers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getLoyaltyProgramTier({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("getLoyaltyProgramTier (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tiers")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getLoyaltyProgramTier({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("getLoyaltyProgramTier (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/loyalty/tier/programs/pid/tiers")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.getLoyaltyProgramTier({
                pid: "pid",
            });
        }).rejects.toThrow(BrevoApi.InternalServerError);
    });

    test("updateTier (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}], name: "name", tierRewards: [{}] };
        const rawResponseBody = {
            accessConditions: [
                {
                    balanceDefinitionId: "balanceDefinitionId",
                    createdAt: "2024-01-15T09:30:00Z",
                    minimumValue: 1,
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            createdAt: "2024-01-15T09:30:00Z",
            groupId: "groupId",
            imageRef: "imageRef",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierId: "tierId",
            tierRewards: [
                { createdAt: "2024-01-15T09:30:00Z", rewardId: "rewardId", updatedAt: "2024-01-15T09:30:00Z" },
            ],
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tiers/tid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tier.updateTier({
            pid: "pid",
            tid: "tid",
            accessConditions: [{}],
            name: "name",
            tierRewards: [{}],
        });
        expect(response).toEqual({
            accessConditions: [
                {
                    balanceDefinitionId: "balanceDefinitionId",
                    createdAt: "2024-01-15T09:30:00Z",
                    minimumValue: 1,
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            createdAt: "2024-01-15T09:30:00Z",
            groupId: "groupId",
            imageRef: "imageRef",
            loyaltyProgramId: "loyaltyProgramId",
            name: "name",
            tierId: "tierId",
            tierRewards: [
                {
                    createdAt: "2024-01-15T09:30:00Z",
                    rewardId: "rewardId",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("updateTier (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name", tierRewards: [{}, {}] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tiers/tid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTier({
                pid: "pid",
                tid: "tid",
                accessConditions: [{}, {}],
                name: "name",
                tierRewards: [{}, {}],
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("updateTier (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name", tierRewards: [{}, {}] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tiers/tid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTier({
                pid: "pid",
                tid: "tid",
                accessConditions: [{}, {}],
                name: "name",
                tierRewards: [{}, {}],
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("updateTier (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name", tierRewards: [{}, {}] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tiers/tid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTier({
                pid: "pid",
                tid: "tid",
                accessConditions: [{}, {}],
                name: "name",
                tierRewards: [{}, {}],
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("updateTier (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name", tierRewards: [{}, {}] };
        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tiers/tid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTier({
                pid: "pid",
                tid: "tid",
                accessConditions: [{}, {}],
                name: "name",
                tierRewards: [{}, {}],
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("updateTier (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { accessConditions: [{}, {}], name: "name", tierRewards: [{}, {}] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/loyalty/tier/programs/pid/tiers/tid")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.updateTier({
                pid: "pid",
                tid: "tid",
                accessConditions: [{}, {}],
                name: "name",
                tierRewards: [{}, {}],
            });
        }).rejects.toThrow(BrevoApi.InternalServerError);
    });

    test("deleteTier (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/loyalty/tier/programs/pid/tiers/tid").respondWith().statusCode(200).build();

        const response = await client.tier.deleteTier({
            pid: "pid",
            tid: "tid",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteTier (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tiers/tid")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTier({
                pid: "pid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.UnauthorizedError);
    });

    test("deleteTier (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tiers/tid")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTier({
                pid: "pid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.ForbiddenError);
    });

    test("deleteTier (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tiers/tid")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTier({
                pid: "pid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.NotFoundError);
    });

    test("deleteTier (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tiers/tid")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTier({
                pid: "pid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.UnprocessableEntityError);
    });

    test("deleteTier (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrevoApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/loyalty/tier/programs/pid/tiers/tid")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tier.deleteTier({
                pid: "pid",
                tid: "tid",
            });
        }).rejects.toThrow(BrevoApi.InternalServerError);
    });
});
