// This file was auto-generated by Fern from our API Definition.

import type * as BrevoApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetCouponCollectionsRequest {
    /** Number of documents returned per page */
    limit?: number;
    /** Index of the first document on the page */
    offset?: number;
    /** Sort the results by creation time in ascending/descending order */
    sort?: BrevoApi.GetCouponCollectionsRequestSort;
    /** The field used to sort coupon collections */
    sortBy?: BrevoApi.GetCouponCollectionsRequestSortBy;
}
