# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .update_campaign_status_status import UpdateCampaignStatusStatus


class UpdateCampaignStatus(UniversalBaseModel):
    """
    Status of the campaign
    """

    status: typing.Optional[UpdateCampaignStatusStatus] = pydantic.Field(default=None)
    """
    Note:- **replicateTemplate** status will be available **only for template type campaigns.**
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
