# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_event_request_object_identifiers import CreateEventRequestObjectIdentifiers


class CreateEventRequestObject(UniversalBaseModel):
    """
    Identifiers of the object record associated with this event. Ignored if the object type or identifier for this record does not exist on the account.
    """

    identifiers: typing.Optional[CreateEventRequestObjectIdentifiers] = pydantic.Field(default=None)
    """
    Identifiers for the object.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Type of object (e.g., subscription, vehicle, etc.)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
